#ifndef WASM_H_GENERATED_
#define WASM_H_GENERATED_
/* Automically generated by wasm2c */
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#include "wasm-rt.h"

#ifndef WASM_RT_MODULE_PREFIX
#define WASM_RT_MODULE_PREFIX
#endif

#define WASM_RT_PASTE_(x, y) x ## y
#define WASM_RT_PASTE(x, y) WASM_RT_PASTE_(x, y)
#define WASM_RT_ADD_PREFIX(x) WASM_RT_PASTE(WASM_RT_MODULE_PREFIX, x)

/* TODO(binji): only use stdint.h types in header */
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;

extern void WASM_RT_ADD_PREFIX(init)(void);

/* import: './client_bg.js' '__wbindgen_json_serialize' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbindgen_json_serializeZ_vii)(u32, u32);
/* import: './client_bg.js' '__wbindgen_string_new' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbindgen_string_newZ_iii)(u32, u32);
/* import: './client_bg.js' '__wbindgen_object_drop_ref' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbindgen_object_drop_refZ_vi)(u32);
/* import: './client_bg.js' '__wbindgen_cb_drop' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbindgen_cb_dropZ_ii)(u32);
/* import: './client_bg.js' '__wbindgen_object_clone_ref' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbindgen_object_clone_refZ_ii)(u32);
/* import: './client_bg.js' '__wbg_new_d4a8512c351e5299' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_new_d4a8512c351e5299Z_iii)(u32, u32);
/* import: './client_bg.js' '__wbg_loadTimes_4e24ad5f8e3d2884' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_loadTimes_4e24ad5f8e3d2884Z_vv)(void);
/* import: './client_bg.js' '__wbg_toString_f0c7462ac29ba762' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_toString_f0c7462ac29ba762Z_vi)(u32);
/* import: './client_bg.js' '__wbg_instanceof_Window_b99429ec408dcb8d' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_instanceof_Window_b99429ec408dcb8dZ_ii)(u32);
/* import: './client_bg.js' '__wbg_getChannelData_597874889a4d8e21' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_getChannelData_597874889a4d8e21Z_viii)(u32, u32, u32);
/* import: './client_bg.js' '__wbg_connect_95a5185b088a32ed' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_connect_95a5185b088a32edZ_iii)(u32, u32);
/* import: './client_bg.js' '__wbg_setvalue_f155d486665c666c' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_setvalue_f155d486665c666cZ_vif)(u32, f32);
/* import: './client_bg.js' '__wbg_instanceof_CanvasRenderingContext2d_cf60543e642e5a93' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_instanceof_CanvasRenderingContext2d_cf60543e642e5a93Z_ii)(u32);
/* import: './client_bg.js' '__wbg_fillStyle_3d31d929bbe8a2f5' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_fillStyle_3d31d929bbe8a2f5Z_ii)(u32);
/* import: './client_bg.js' '__wbg_beginPath_790cd831253a2637' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_beginPath_790cd831253a2637Z_vi)(u32);
/* import: './client_bg.js' '__wbg_stroke_cd9ee78b96e12894' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_stroke_cd9ee78b96e12894Z_vi)(u32);
/* import: './client_bg.js' '__wbg_fillText_fdd6d14e79f143f3' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_fillText_fdd6d14e79f143f3Z_viiidd)(u32, u32, u32, f64, f64);
/* import: './client_bg.js' '__wbg_documentElement_3932e3004b15af7f' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_documentElement_3932e3004b15af7fZ_ii)(u32);
/* import: './client_bg.js' '__wbg_createElement_1959ce882284e011' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_createElement_1959ce882284e011Z_iiii)(u32, u32, u32);
/* import: './client_bg.js' '__wbg_getElementById_f059b7401a23ee7c' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_getElementById_f059b7401a23ee7cZ_iiii)(u32, u32, u32);
/* import: './client_bg.js' '__wbg_threshold_cd658be40c7cf1c9' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_threshold_cd658be40c7cf1c9Z_ii)(u32);
/* import: './client_bg.js' '__wbg_knee_0fc297d108215002' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_knee_0fc297d108215002Z_ii)(u32);
/* import: './client_bg.js' '__wbg_ratio_3cda99bef9c9de02' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_ratio_3cda99bef9c9de02Z_ii)(u32);
/* import: './client_bg.js' '__wbg_attack_c15ff8a23c3b36c1' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_attack_c15ff8a23c3b36c1Z_ii)(u32);
/* import: './client_bg.js' '__wbg_release_2418f7eb47df069d' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_release_2418f7eb47df069dZ_ii)(u32);
/* import: './client_bg.js' '__wbg_hasAttribute_c831cb47fd0a093a' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_hasAttribute_c831cb47fd0a093aZ_iiii)(u32, u32, u32);
/* import: './client_bg.js' '__wbg_setAttribute_c44888e5d6dd5133' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_setAttribute_c44888e5d6dd5133Z_viiiii)(u32, u32, u32, u32, u32);
/* import: './client_bg.js' '__wbg_instanceof_HtmlCanvasElement_a2acc34cc0a30700' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_instanceof_HtmlCanvasElement_a2acc34cc0a30700Z_ii)(u32);
/* import: './client_bg.js' '__wbg_getContext_c91489f5e0f738d8' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_getContext_c91489f5e0f738d8Z_iiii)(u32, u32, u32);
/* import: './client_bg.js' '__wbg_toDataURL_fe2ebea8b463e5de' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_toDataURL_fe2ebea8b463e5deZ_vii)(u32, u32);
/* import: './client_bg.js' '__wbg_plugins_320bace199ef9abf' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_plugins_320bace199ef9abfZ_ii)(u32);
/* import: './client_bg.js' '__wbg_platform_1e434a0f557294e0' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_platform_1e434a0f557294e0Z_vii)(u32, u32);
/* import: './client_bg.js' '__wbg_userAgent_9206fc4778d7ddbf' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_userAgent_9206fc4778d7ddbfZ_vii)(u32, u32);
/* import: './client_bg.js' '__wbg_language_f050e03d2e52b258' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_language_f050e03d2e52b258Z_vii)(u32, u32);
/* import: './client_bg.js' '__wbg_instanceof_OfflineAudioCompletionEvent_701cd78a54c2de68' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_instanceof_OfflineAudioCompletionEvent_701cd78a54c2de68Z_ii)(u32);
/* import: './client_bg.js' '__wbg_renderedBuffer_893e63ccf50c341b' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_renderedBuffer_893e63ccf50c341bZ_ii)(u32);
/* import: './client_bg.js' '__wbg_setoncomplete_df3e7572053c3f55' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_setoncomplete_df3e7572053c3f55Z_vii)(u32, u32);
/* import: './client_bg.js' '__wbg_destination_d4bc891fa34ade75' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_destination_d4bc891fa34ade75Z_ii)(u32);
/* import: './client_bg.js' '__wbg_newwithnumberofchannelsandlengthandsamplerate_68f2f3eda78ae0fb' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_newwithnumberofchannelsandlengthandsamplerate_68f2f3eda78ae0fbZ_iiif)(u32, u32, f32);
/* import: './client_bg.js' '__wbg_startRendering_6e86803227d84e1a' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_startRendering_6e86803227d84e1aZ_ii)(u32);
/* import: './client_bg.js' '__wbg_createDynamicsCompressor_733dc92a9a7b9f0a' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_createDynamicsCompressor_733dc92a9a7b9f0aZ_ii)(u32);
/* import: './client_bg.js' '__wbg_createOscillator_07fc6070e0927b13' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_createOscillator_07fc6070e0927b13Z_ii)(u32);
/* import: './client_bg.js' '__wbg_settype_74b3c476d82b7d81' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_settype_74b3c476d82b7d81Z_vii)(u32, u32);
/* import: './client_bg.js' '__wbg_frequency_8bb0ba0f358f0df3' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_frequency_8bb0ba0f358f0df3Z_ii)(u32);
/* import: './client_bg.js' '__wbg_start_4e974abb239113a5' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_start_4e974abb239113a5Z_vi)(u32);
/* import: './client_bg.js' '__wbg_availWidth_52ce20c430bfe00d' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_availWidth_52ce20c430bfe00dZ_ii)(u32);
/* import: './client_bg.js' '__wbg_availHeight_5a38eff40ca35e9b' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_availHeight_5a38eff40ca35e9bZ_ii)(u32);
/* import: './client_bg.js' '__wbg_width_85d397e0585a43f5' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_width_85d397e0585a43f5Z_ii)(u32);
/* import: './client_bg.js' '__wbg_height_ec1147d0b6442a92' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_height_ec1147d0b6442a92Z_ii)(u32);
/* import: './client_bg.js' '__wbg_colorDepth_2dc95ec7a52b996f' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_colorDepth_2dc95ec7a52b996fZ_ii)(u32);
/* import: './client_bg.js' '__wbg_pixelDepth_c6ae77d65aa9cf0a' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_pixelDepth_c6ae77d65aa9cf0aZ_ii)(u32);
/* import: './client_bg.js' '__wbg_instanceof_WebGlRenderingContext_818d472bc7c5b45f' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_instanceof_WebGlRenderingContext_818d472bc7c5b45fZ_ii)(u32);
/* import: './client_bg.js' '__wbg_bufferData_73b03d31508caaaf' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_bufferData_73b03d31508caaafZ_viiii)(u32, u32, u32, u32);
/* import: './client_bg.js' '__wbg_attachShader_fa6cb82d8c156e97' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_attachShader_fa6cb82d8c156e97Z_viii)(u32, u32, u32);
/* import: './client_bg.js' '__wbg_bindBuffer_2b82f93e9937093c' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_bindBuffer_2b82f93e9937093cZ_viii)(u32, u32, u32);
/* import: './client_bg.js' '__wbg_clear_2408507f739a1729' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_clear_2408507f739a1729Z_vii)(u32, u32);
/* import: './client_bg.js' '__wbg_clearColor_18646442c5e0c40b' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_clearColor_18646442c5e0c40bZ_viffff)(u32, f32, f32, f32, f32);
/* import: './client_bg.js' '__wbg_compileShader_287622338d6be95d' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_compileShader_287622338d6be95dZ_vii)(u32, u32);
/* import: './client_bg.js' '__wbg_createBuffer_301ddfe22095bd60' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_createBuffer_301ddfe22095bd60Z_ii)(u32);
/* import: './client_bg.js' '__wbg_createProgram_4c9163cf7c010649' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_createProgram_4c9163cf7c010649Z_ii)(u32);
/* import: './client_bg.js' '__wbg_createShader_ef7fcb3e55370057' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_createShader_ef7fcb3e55370057Z_iii)(u32, u32);
/* import: './client_bg.js' '__wbg_drawArrays_868fe6a90f7b1043' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_drawArrays_868fe6a90f7b1043Z_viiii)(u32, u32, u32, u32);
/* import: './client_bg.js' '__wbg_enableVertexAttribArray_dcee80acac2910f7' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_enableVertexAttribArray_dcee80acac2910f7Z_vii)(u32, u32);
/* import: './client_bg.js' '__wbg_getProgramInfoLog_012c9ebabe30d2cf' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_getProgramInfoLog_012c9ebabe30d2cfZ_viii)(u32, u32, u32);
/* import: './client_bg.js' '__wbg_getProgramParameter_d431315afbb77963' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_getProgramParameter_d431315afbb77963Z_iiii)(u32, u32, u32);
/* import: './client_bg.js' '__wbg_getShaderInfoLog_1bef679e6581491f' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_getShaderInfoLog_1bef679e6581491fZ_viii)(u32, u32, u32);
/* import: './client_bg.js' '__wbg_getShaderParameter_19926666f0459139' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_getShaderParameter_19926666f0459139Z_iiii)(u32, u32, u32);
/* import: './client_bg.js' '__wbg_getSupportedExtensions_74159fa993544c6e' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_getSupportedExtensions_74159fa993544c6eZ_ii)(u32);
/* import: './client_bg.js' '__wbg_linkProgram_918ebd99ab29b2a0' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_linkProgram_918ebd99ab29b2a0Z_vii)(u32, u32);
/* import: './client_bg.js' '__wbg_shaderSource_1438d7b94567fe90' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_shaderSource_1438d7b94567fe90Z_viiii)(u32, u32, u32, u32);
/* import: './client_bg.js' '__wbg_useProgram_6178163060023ecb' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_useProgram_6178163060023ecbZ_vii)(u32, u32);
/* import: './client_bg.js' '__wbg_vertexAttribPointer_7622b60482e53ba1' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_vertexAttribPointer_7622b60482e53ba1Z_viiiiiii)(u32, u32, u32, u32, u32, u32, u32);
/* import: './client_bg.js' '__wbg_document_6d5890b86bbf5b96' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_document_6d5890b86bbf5b96Z_ii)(u32);
/* import: './client_bg.js' '__wbg_navigator_bc0b459c4b6dbe01' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_navigator_bc0b459c4b6dbe01Z_ii)(u32);
/* import: './client_bg.js' '__wbg_screen_563041f109418bcc' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_screen_563041f109418bccZ_ii)(u32);
/* import: './client_bg.js' '__wbg_localStorage_fbbeeb3a3dfd5be3' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_localStorage_fbbeeb3a3dfd5be3Z_ii)(u32);
/* import: './client_bg.js' '__wbg_indexedDB_acff057640f0088f' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_indexedDB_acff057640f0088fZ_ii)(u32);
/* import: './client_bg.js' '__wbg_sessionStorage_305af71f8a4df982' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_sessionStorage_305af71f8a4df982Z_ii)(u32);
/* import: './client_bg.js' '__wbg_get_e7022d8fa5682598' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_get_e7022d8fa5682598Z_iiii)(u32, u32, u32);
/* import: './client_bg.js' '__wbg_clearTimeout_ce814860980d15a3' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_clearTimeout_ce814860980d15a3Z_vii)(u32, u32);
/* import: './client_bg.js' '__wbg_setTimeout_2a8d37ca95b952e7' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_setTimeout_2a8d37ca95b952e7Z_iiii)(u32, u32, u32);
/* import: './client_bg.js' '__wbg_self_86b4b13392c7af56' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_self_86b4b13392c7af56Z_iv)(void);
/* import: './client_bg.js' '__wbg_crypto_b8c92eaac23d0d80' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_crypto_b8c92eaac23d0d80Z_ii)(u32);
/* import: './client_bg.js' '__wbg_msCrypto_9ad6677321a08dd8' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_msCrypto_9ad6677321a08dd8Z_ii)(u32);
/* import: './client_bg.js' '__wbindgen_is_undefined' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbindgen_is_undefinedZ_ii)(u32);
/* import: './client_bg.js' '__wbg_static_accessor_MODULE_452b4680e8614c81' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_static_accessor_MODULE_452b4680e8614c81Z_iv)(void);
/* import: './client_bg.js' '__wbg_require_f5521a5b85ad2542' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_require_f5521a5b85ad2542Z_iiii)(u32, u32, u32);
/* import: './client_bg.js' '__wbg_getRandomValues_dd27e6b0652b3236' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_getRandomValues_dd27e6b0652b3236Z_ii)(u32);
/* import: './client_bg.js' '__wbg_randomFillSync_d2ba53160aec6aba' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_randomFillSync_d2ba53160aec6abaZ_viii)(u32, u32, u32);
/* import: './client_bg.js' '__wbg_getRandomValues_e57c9b75ddead065' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_getRandomValues_e57c9b75ddead065Z_vii)(u32, u32);
/* import: './client_bg.js' '__wbg_get_a4f61a2fb16987bc' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_get_a4f61a2fb16987bcZ_iii)(u32, u32);
/* import: './client_bg.js' '__wbg_length_f86925e8c69110ea' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_length_f86925e8c69110eaZ_ii)(u32);
/* import: './client_bg.js' '__wbg_newnoargs_68424965d85fcb08' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_newnoargs_68424965d85fcb08Z_iii)(u32, u32);
/* import: './client_bg.js' '__wbg_get_75d36ef8b2e1d918' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_get_75d36ef8b2e1d918Z_iii)(u32, u32);
/* import: './client_bg.js' '__wbg_call_9698e9b9c4668ae0' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_call_9698e9b9c4668ae0Z_iii)(u32, u32);
/* import: './client_bg.js' '__wbg_new_ffb8fbe0ad5d4d2f' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_new_ffb8fbe0ad5d4d2fZ_iv)(void);
/* import: './client_bg.js' '__wbg_instanceof_Error_ac0db369f0645066' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_instanceof_Error_ac0db369f0645066Z_ii)(u32);
/* import: './client_bg.js' '__wbg_toString_b2da48ab6ca0c44d' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_toString_b2da48ab6ca0c44dZ_ii)(u32);
/* import: './client_bg.js' '__wbg_call_4438b4bab9ab5268' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_call_4438b4bab9ab5268Z_iiii)(u32, u32, u32);
/* import: './client_bg.js' '__wbg_construct_8fcba71a7eab4ec1' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_construct_8fcba71a7eab4ec1Z_iii)(u32, u32);
/* import: './client_bg.js' '__wbg_defineProperty_c324da7a0b2d7d18' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_defineProperty_c324da7a0b2d7d18Z_iiii)(u32, u32, u32);
/* import: './client_bg.js' '__wbg_getOwnPropertyDescriptor_24aa7e693dd9e2da' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_getOwnPropertyDescriptor_24aa7e693dd9e2daZ_iii)(u32, u32);
/* import: './client_bg.js' '__wbg_has_d87073f723676bd5' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_has_d87073f723676bd5Z_iii)(u32, u32);
/* import: './client_bg.js' '__wbg_ownKeys_df13b91d66111202' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_ownKeys_df13b91d66111202Z_ii)(u32);
/* import: './client_bg.js' '__wbg_set_c7fc8735d70ceb11' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_set_c7fc8735d70ceb11Z_iiii)(u32, u32, u32);
/* import: './client_bg.js' '__wbg_buffer_eb2155f17856c20b' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_buffer_eb2155f17856c20bZ_ii)(u32);
/* import: './client_bg.js' '__wbg_new_ae366b99da42660b' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_new_ae366b99da42660bZ_iii)(u32, u32);
/* import: './client_bg.js' '__wbg_resolve_84f06d050082a771' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_resolve_84f06d050082a771Z_ii)(u32);
/* import: './client_bg.js' '__wbg_then_fd35af33296a58d7' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_then_fd35af33296a58d7Z_iii)(u32, u32);
/* import: './client_bg.js' '__wbg_then_c919ca41618a24c2' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_then_c919ca41618a24c2Z_iiii)(u32, u32, u32);
/* import: './client_bg.js' '__wbg_self_3df7c33e222cd53b' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_self_3df7c33e222cd53bZ_iv)(void);
/* import: './client_bg.js' '__wbg_window_0f90182e6c405ff2' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_window_0f90182e6c405ff2Z_iv)(void);
/* import: './client_bg.js' '__wbg_globalThis_787cfd4f25a35141' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_globalThis_787cfd4f25a35141Z_iv)(void);
/* import: './client_bg.js' '__wbg_global_af2eb7b1369372ed' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_global_af2eb7b1369372edZ_iv)(void);
/* import: './client_bg.js' '__wbg_length_0b194abde938d0c6' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_length_0b194abde938d0c6Z_ii)(u32);
/* import: './client_bg.js' '__wbg_new_ff8b26f7b2d7e2fb' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_new_ff8b26f7b2d7e2fbZ_ii)(u32);
/* import: './client_bg.js' '__wbg_set_67cdd115b9cb141f' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_set_67cdd115b9cb141fZ_viii)(u32, u32, u32);
/* import: './client_bg.js' '__wbg_newwithbyteoffsetandlength_a0eded3bb0192ce6' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_newwithbyteoffsetandlength_a0eded3bb0192ce6Z_iiii)(u32, u32, u32);
/* import: './client_bg.js' '__wbg_newwithlength_a49b32b2030b93c3' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_newwithlength_a49b32b2030b93c3Z_ii)(u32);
/* import: './client_bg.js' '__wbg_subarray_1bb315d30e0c968c' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbg_subarray_1bb315d30e0c968cZ_iiii)(u32, u32, u32);
/* import: './client_bg.js' '__wbindgen_number_get' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbindgen_number_getZ_vii)(u32, u32);
/* import: './client_bg.js' '__wbindgen_string_get' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbindgen_string_getZ_vii)(u32, u32);
/* import: './client_bg.js' '__wbindgen_boolean_get' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbindgen_boolean_getZ_ii)(u32);
/* import: './client_bg.js' '__wbindgen_debug_string' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbindgen_debug_stringZ_vii)(u32, u32);
/* import: './client_bg.js' '__wbindgen_throw' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbindgen_throwZ_vii)(u32, u32);
/* import: './client_bg.js' '__wbindgen_rethrow' */
extern void (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbindgen_rethrowZ_vi)(u32);
/* import: './client_bg.js' '__wbindgen_memory' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbindgen_memoryZ_iv)(void);
/* import: './client_bg.js' '__wbindgen_closure_wrapper153' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbindgen_closure_wrapper153Z_iiii)(u32, u32, u32);
/* import: './client_bg.js' '__wbindgen_closure_wrapper155' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbindgen_closure_wrapper155Z_iiii)(u32, u32, u32);
/* import: './client_bg.js' '__wbindgen_closure_wrapper157' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbindgen_closure_wrapper157Z_iiii)(u32, u32, u32);
/* import: './client_bg.js' '__wbindgen_closure_wrapper266' */
extern u32 (*Z_Z2EZ2Fclient_bgZ2EjsZ___wbindgen_closure_wrapper266Z_iiii)(u32, u32, u32);

/* export: '__wbindgen_export_2' */
extern wasm_rt_table_t (*WASM_RT_ADD_PREFIX(Z___wbindgen_export_2));
/* export: 'memory' */
extern wasm_rt_memory_t (*WASM_RT_ADD_PREFIX(Z_memory));
/* export: 'client' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_clientZ_iiii))(u32, u32, u32);
/* export: '_dyn_core__ops__function__FnMut__A_B___Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h41b2227b4d613617' */
extern u32 (*WASM_RT_ADD_PREFIX(Z__dyn_core__ops__function__FnMut__A_B___Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h41b2227b4d613617Z_iiiii))(u32, u32, u32, u32);
/* export: '__wbindgen_malloc' */
extern u32 (*WASM_RT_ADD_PREFIX(Z___wbindgen_mallocZ_ii))(u32);
/* export: '__wbindgen_realloc' */
extern u32 (*WASM_RT_ADD_PREFIX(Z___wbindgen_reallocZ_iiii))(u32, u32, u32);
/* export: 'wasm_bindgen__convert__closures__invoke2_mut__h18dd75cf7a9acbd4' */
extern void (*WASM_RT_ADD_PREFIX(Z_wasm_bindgen__convert__closures__invoke2_mut__h18dd75cf7a9acbd4Z_viiii))(u32, u32, u32, u32);
/* export: '_dyn_core__ops__function__Fn__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__he91395b52773db2b' */
extern void (*WASM_RT_ADD_PREFIX(Z__dyn_core__ops__function__Fn__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__he91395b52773db2bZ_viii))(u32, u32, u32);
/* export: '_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hba165590be79d689' */
extern void (*WASM_RT_ADD_PREFIX(Z__dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hba165590be79d689Z_viii))(u32, u32, u32);
/* export: '_dyn_core__ops__function__Fn_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h1dd795b129347279' */
extern void (*WASM_RT_ADD_PREFIX(Z__dyn_core__ops__function__Fn_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h1dd795b129347279Z_vii))(u32, u32);
/* export: '__wbindgen_exn_store' */
extern void (*WASM_RT_ADD_PREFIX(Z___wbindgen_exn_storeZ_vi))(u32);
#ifdef __cplusplus
}
#endif

#endif 